export const ADD_NEW_POST = 'POST/ADD_NEW_POST';
export const RENDER_FETCHED_POSTS = 'POST/RENDER_FETCHED_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
